### ISSUE TITLE
Optical flow for feature tracking

### ISSUE THREAD

**Issue by weisongwen** [cashiwamochi/LK20_ImageAlignment#1]
hi @cashiwamochi , Thanks for sharing such a nice work. Could you kindly provide some suggestions if I want to track two features in two images based on your code? 

Currently, I want to test the feature tracking using optical flow. In other words, I would like to achieve the function as the function "[calcOpticalFlowPyrLK](https://github.com/HKUST-Aerial-Robotics/VINS-Fusion/blob/master/vins_estimator/src/featureTracker/feature_tracker.cpp#L139)", but I do want to use the calcOpticalFlowPyrLK function directly from the OpenCV library. 

Thanks a lot in advance,

Best,
Weisong,

**Comment by cashiwamochi** [comment]
Hello, Weisong

If you want to use this algorithm in feature tracking, firstly we have to make sure that this optimization works with small patch (e.g. 21x21). If it works, we can track features like SVO( http://rpg.ifi.uzh.ch/docs/ICRA14_Forster.pdf, Sec4.B ).

Maybe it's possible to make the argument of function same as calcOpticalFlowPyrLK, but it's easy to use define macro. Otherwise you have to modify OpenCV and re-build it.

Thanks

**Comment by weisongwen** [comment]
Hi @cashiwamochi , Thanks for your kind reply. I am sorry that I did not correct explain my question. In fact, I do not want to direct use the function "calcOpticalFlowPyrLK " in OpenCV due to some reasons. Thanks for your great code, I expect to implement the **_calcOpticalFlowPyrLK_** for feature tracking based on your code (this package). Currently, your code is used for planar tracking. My understanding is that your code is used to track the certain planar area, kindly please correct me if I am not correct :-)

Therefore, if I want to track, for example 10 features with patch size of  (e.g. 21x21). Could you please kindly let me know roughly how should I achieve this? 

Thanks a lot in advance.

Best,
Weisong,

**Comment by cashiwamochi** [comment]
Thanks @weisongwen for kind explanation.

Now I understand what you want to do.

> My understanding is that your code is used to track the certain planar area

Yes, this is correct. Additionally let me note that, this implementation is different from the algorithm of calcOpticalFlowPyrLK. The former minimizes photometric error iteratively and the latter just solves equation. ( If my knowledge about OpenCV isn't too old )

>  Could you please kindly let me know roughly how should I achieve this?

As I commented, firstly we need to make sure that this implementation works with small patch. 
If it works, we need to re-write API of this algorithm, because actually this program is implemented to track only one planar image to show performance of Lucas-Kanade's image alignment. 

By the way, we need to think about how to use image pyramid. But this work would be done after those above action items.
If you need support, I will work on this issue when I have time.

Thanks.

**Comment by weisongwen** [comment]
Dear @cashiwamochi,

Thanks for your kind reply and sorry for my late reply as I spend some time to look into your code before replying you 👍 

I find that your code does not work with the smaller patch (e.g. one pixel). I will implement the multi-layers pyramids for optical tracking in the coming week. I will let you know if I got some issues or finish this. 

Best,
Weisong,

**Comment by cashiwamochi** [comment]
Hello @weisongwen 

> I find that your code does not work with the smaller patch (e.g. one pixel).

Theoretically, this algorithm never work with one pixel patch. When it tries to track a patch from frameA to frameB, patch in frameB must be overlapped partially with patch in frameA. 
( Sorry, I wrote this just in case so that you never make any mistake about it )

>  I will let you know if I got some issues or finish this.

Let me close the issue now. When you have any topic or issue, please reopen.

Thanks

**Comment by weisongwen** [comment]
Hi @cashiwamochi ,

Thanks for your kind reply. I will let you know if I got any updates 👍 

Best,
Weisong,

**Comment by qilintong** [comment]
error:M_PI未声明的标识符
